apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-events-event-watcher
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-event-watcher-binding
roleRef:
  kind: ClusterRole
  name: argo-events-event-watcher
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
    namespace: argo-events