apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kyverno-policy-events
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
    container:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
  eventBusName: default
  resource:
    kyverno-events:
      version: v1
      resource: events
      eventTypes:
        - ADD
        - UPDATE
      filter:
        fields:
          - key: reason
            value: "PolicyViolation"
          - key: type
            value: "Warning"