apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-events-policyreport-reader
rules:
  - apiGroups: ["wgpolicyk8s.io"]
    resources: ["policyreports"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-policyreport-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-policyreport-reader
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
    namespace: argo-events
